language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "pypy"
  - "pypy3"
install: pip install -r requirements.txt &&  python setup.py develop
script:  python tests/delorean_tests.py
